package com.bdaim.crm.erp.oa.entity;

import com.bdaim.crm.erp.oa.entity.base.BaseOaActionRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaActionRecord extends BaseOaActionRecord<OaActionRecord> {
	public static final OaActionRecord dao = new OaActionRecord().dao();
}
