package com.bdaim.crm.erp.oa.entity;

import com.bdaim.crm.erp.oa.entity.base.BaseOaExamineStep;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamineStep extends BaseOaExamineStep<OaExamineStep> {
	public static final OaExamineStep dao = new OaExamineStep().dao();
}
