package com.bdaim.crm.erp.oa.entity;

import com.bdaim.crm.erp.oa.entity.base.BaseOaExamineCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamineCategory extends BaseOaExamineCategory<OaExamineCategory> {
	public static final OaExamineCategory dao = new OaExamineCategory().dao();
}
