package com.bdaim.crm.erp.oa.entity;

import com.bdaim.crm.erp.oa.entity.base.BaseOaExamineLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamineLog extends BaseOaExamineLog<OaExamineLog> {
	public static final OaExamineLog dao = new OaExamineLog().dao();
}
