package com.bdaim.crm.erp.oa.entity;

import com.bdaim.crm.erp.oa.entity.base.BaseOaExamineRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamineRelation extends BaseOaExamineRelation<OaExamineRelation> {
	public static final OaExamineRelation dao = new OaExamineRelation().dao();
}
