server:
  port: 8081
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: dev
    password: dev__807
    url: jdbc:mysql://192.168.32.200/label?characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://127.0.0.1/label?characterEncoding=utf-8&useSSL=false
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 15
      connection-timeout: 3000
      connection-test-query: select 1
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        new_generator_mappings: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        format_sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
logging:
  level: 
    org.hibernate: INFO
    com.bdaim: DEBUG
  file: bp.log
file:
  file_path: /data/file
express:
  zto:
    url: http://japi.zto.cn/exposeServicePushOrderService
    company_id: 295a3076000345b58ca82820113ecb95
    key: 9457a158dc5e
    shopKey: QUNFNjAwNzhCNDU0ODMzNTY1NDA0NjUzRTEzRUVGMEM=

#云讯短信通道参数
ytx:
  spuid: 469
  sppwd: 108492

app: online