server:
  port: 8081
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: dev
    password: dev__807
    url: jdbc:mysql://192.168.32.200/label?characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://127.0.0.1/label?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        new_generator_mappings: false
        format_sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.32.200
    port: 6379