package com.bdaim.crm.erp.work.entity;

import com.bdaim.crm.erp.work.entity.base.BaseTaskRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskRelation extends BaseTaskRelation<TaskRelation> {
	public static final TaskRelation dao = new TaskRelation().dao();
}
