package com.bdaim.crm.erp.work.entity;


import com.bdaim.crm.erp.work.entity.base.BaseWorkUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkUser extends BaseWorkUser<WorkUser> {
	public static final WorkUser dao = new WorkUser().dao();
}
