package com.bdaim.crm.erp.work.entity;

import com.bdaim.crm.erp.work.entity.base.BaseWorkTaskLabel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkTaskLabel extends BaseWorkTaskLabel<WorkTaskLabel>{
	public static final WorkTaskLabel dao = new WorkTaskLabel().dao();
}
