package com.bdaim.crm.erp.work.entity;

import com.bdaim.crm.erp.work.entity.base.BaseWork;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Work extends BaseWork<Work> {
	public static final Work dao = new Work().dao();
}
