package com.bdaim.crm.erp.admin.entity;


import com.bdaim.crm.erp.admin.entity.base.BaseAdminConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminConfig extends BaseAdminConfig<AdminConfig> {
	public static final AdminConfig dao = new AdminConfig().dao();
}
