package com.bdaim.crm.erp.admin.entity;

import com.bdaim.crm.erp.admin.entity.base.BaseAdminFieldv;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminFieldv extends BaseAdminFieldv<AdminFieldv> {
	public static final AdminFieldv dao = new AdminFieldv().dao();
}
