package com.bdaim.crm.erp.admin.entity;

import com.bdaim.crm.erp.admin.entity.base.BaseAdminExamineLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminExamineLog extends BaseAdminExamineLog<AdminExamineLog> {
	public static final AdminExamineLog dao = new AdminExamineLog().dao();
}
