package com.bdaim.crm.erp.admin.entity;

import com.bdaim.crm.erp.admin.entity.base.BaseAdminSceneDefault;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminSceneDefault extends BaseAdminSceneDefault<AdminSceneDefault> {
	public static final AdminSceneDefault dao = new AdminSceneDefault().dao();
}
