package com.bdaim.crm.erp.admin.entity;

import com.bdaim.crm.erp.admin.entity.base.BaseCrmBusinessStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBusinessStatus extends BaseCrmBusinessStatus<CrmBusinessStatus> {
	public static final CrmBusinessStatus dao = new CrmBusinessStatus().dao();
}
