package com.bdaim.crm.erp.crm.entity;

import com.bdaim.crm.erp.crm.entity.base.BaseCrmContractProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmContractProduct extends BaseCrmContractProduct<CrmContractProduct> {
	public static final CrmContractProduct dao = new CrmContractProduct().dao();
}
