package com.bdaim.crm.erp.crm.entity;

import com.bdaim.crm.erp.crm.entity.base.BaseCrmOwnerRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmOwnerRecord extends BaseCrmOwnerRecord<CrmOwnerRecord> {
	public static final CrmOwnerRecord dao = new CrmOwnerRecord().dao();
}
